[package]
name = "london_tennis_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.22"
chrono = "0.4"
tokio = { version = "1.43", features = ["full"] }