[package]
name = "london_tennis_web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
london_tennis_scraper = { workspace = true }
reqwest = { version = "0.12"}
tokio = { version = "1", features = ["full"] }