[package]
name = "london-tennis-web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
london-tennis-scraper = { workspace = true }
reqwest = { version = "0.12"}
tokio = { version = "1.43", features = ["full"] }
actix-web = "4"
actix-files = "0.6"